--- #YAML:1.0
name:               IO-Socket-SSL
version:            2.002
abstract:           Nearly transparent SSL encapsulation for IO::Socket::INET.
author:
    - Steffen Ullrich <sullr@cpan.org>, Peter Behroozi, Marko Asplund
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::SSLeay:   1.46
    Scalar::Util:  0
resources:
    bugtracker:  https://rt.cpan.org/Dist/Display.html?Queue=IO-Socket-SSL
    homepage:    https://github.com/noxxi/p5-io-socket-ssl
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/noxxi/p5-io-socket-ssl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
