--- #YAML:1.0
name:               IO-Socket-SSL
version:            1.40
abstract:           Nearly transparent SSL encapsulation for IO::Socket::INET.
author:
    - Steffen Ullrich & Peter Behroozi & Marko Asplund
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::SSLeay:   1.21
    Scalar::Util:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
