# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-Socket-SSL
version:      0.99
version_from: SSL.pm
installdirs:  site
license: perl
requires:
    Net::SSLeay:                   1.21

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
